import React, { useEffect, useState } from "react";
import { getAdaptivePlan } from "../services/api";

const AdaptivePlan = () => {

    const [plan, setPlan] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    const loadAdaptivePlan = async () => {

        try {

            setLoading(true);
            setError("");

            const response = await getAdaptivePlan();

            setPlan(response.data);

        } catch (error) {

            console.error("Failed to load adaptive plan:", error);

            setError(
                "Unable to load your adaptive plan. Please try again."
            );

        } finally {

            setLoading(false);

        }
    };


    useEffect(() => {
        loadAdaptivePlan();
    }, []);


    if (loading) {
        return (
            <div className="max-w-6xl mx-auto">

                <div className="mb-8">
                    <h1 className="text-3xl font-bold">
                        🧠 Adaptive AI Plan
                    </h1>

                    <p className="text-muted text-sm mt-1">
                        AI is analyzing your fitness activity and goals...
                    </p>
                </div>

                <div className="p-8 rounded-2xl bg-surface border border-border animate-pulse">

                    <div className="h-5 w-1/3 bg-border rounded mb-4" />

                    <div className="h-4 w-full bg-border rounded mb-3" />

                    <div className="h-4 w-5/6 bg-border rounded mb-3" />

                    <div className="h-4 w-4/6 bg-border rounded" />

                </div>

            </div>
        );
    }


    if (error) {
        return (
            <div className="max-w-6xl mx-auto">

                <div className="p-8 rounded-2xl bg-surface border border-red-500/30 text-center">

                    <div className="text-4xl mb-3">
                        ⚠️
                    </div>

                    <h2 className="font-semibold mb-2">
                        Unable to Load Adaptive Plan
                    </h2>

                    <p className="text-sm text-muted mb-5">
                        {error}
                    </p>

                    <button
                        onClick={loadAdaptivePlan}
                        className="px-5 py-2.5 rounded-lg bg-primary text-bg font-semibold hover:opacity-90 transition"
                    >
                        Try Again
                    </button>

                </div>

            </div>
        );
    }


    if (!plan) {
        return null;
    }


    return (
        <div className="max-w-6xl mx-auto">

            {/* Header */}
            <div className="mb-8">

                <div className="flex items-center gap-3">

                    <div className="w-12 h-12 rounded-xl bg-primary/10 border border-primary/30 flex items-center justify-center text-2xl">
                        🧠
                    </div>

                    <div>
                        <h1 className="text-3xl font-bold tracking-tight">
                            Adaptive AI Plan
                        </h1>

                        <p className="text-muted text-sm mt-1">
                            Your personalized fitness strategy generated by AI.
                        </p>
                    </div>

                </div>

            </div>


            {/* Analysis */}
            <div className="p-6 rounded-2xl bg-surface border border-border mb-6">

                <h2 className="text-lg font-semibold mb-3 flex items-center gap-2">
                    📊 Fitness Analysis
                </h2>

                <p className="text-white/85 leading-relaxed text-[15px]">
                    {plan.analysis}
                </p>

            </div>


            {/* Behavior + Goal Status */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">

                {/* Behavior */}
                <div className="p-6 rounded-2xl bg-surface border border-border">

                    <h2 className="text-lg font-semibold mb-3 flex items-center gap-2">
                        🏃 Behavior
                    </h2>

                    <p className="text-white/85 leading-relaxed text-[15px]">
                        {plan.behavior}
                    </p>

                </div>


                {/* Goal Status */}
                <div className="p-6 rounded-2xl bg-surface border border-border">

                    <h2 className="text-lg font-semibold mb-3 flex items-center gap-2">
                        🎯 Goal Status
                    </h2>

                    <p className="text-white/85 leading-relaxed text-[15px]">
                        {plan.goalStatus}
                    </p>

                </div>

            </div>


            {/* Weekly Plan */}
            <div className="mb-6">

                <div className="mb-4">

                    <h2 className="text-2xl font-bold">
                        📅 Your 7-Day Adaptive Plan
                    </h2>

                    <p className="text-muted text-sm mt-1">
                        A personalized weekly workout plan based on your
                        activity history and current goals.
                    </p>

                </div>


                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">

                    {plan.weeklyPlan?.map((day, index) => (

                        <div
                            key={index}
                            className="relative p-6 rounded-2xl bg-surface border border-border hover:border-primary/40 transition"
                        >

                            {/* Day */}
                            <div className="flex items-center justify-between mb-4">

                                <span className="text-sm font-semibold text-primary uppercase tracking-wider">
                                    {day.day}
                                </span>

                                <span className="px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-semibold">
                                    {day.duration} min
                                </span>

                            </div>


                            {/* Activity */}
                            <h3 className="text-xl font-semibold mb-3">
                                {day.activity}
                            </h3>


                            {/* Reason */}
                            <p className="text-sm text-muted leading-relaxed">
                                {day.reason}
                            </p>

                        </div>

                    ))}

                </div>

            </div>


            {/* Suggestions */}
            <div className="p-6 rounded-2xl bg-surface border border-primary/30">

                <div className="flex items-center gap-3 mb-5">

                    <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/30 flex items-center justify-center text-xl">
                        💡
                    </div>

                    <div>

                        <h2 className="font-semibold">
                            AI Suggestions
                        </h2>

                        <p className="text-xs text-muted">
                            Personalized recommendations based on your data
                        </p>

                    </div>

                </div>


                <div className="space-y-3">

                    {plan.suggestions?.map((suggestion, index) => (

                        <div
                            key={index}
                            className="flex gap-3 p-4 rounded-xl bg-bg/50 border border-border"
                        >

                            <span className="text-primary font-bold">
                                {index + 1}.
                            </span>

                            <p className="text-sm text-white/85 leading-relaxed">
                                {suggestion}
                            </p>

                        </div>

                    ))}

                </div>

            </div>

        </div>
    );
};

export default AdaptivePlan;