spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: goal-service-local
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path=/api/goals/**