spring:
  application:
   name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8181/realms/fittrack-oauth2/protocol/openid-connect/certs}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: activity-service
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path=/api/activities/**

            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/recommendations/**

            - id: ai-coach-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/coach/**

            - id: adaptive-ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/adaptive/**


            - id: goal-service
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path=/api/goals/**


          



server:
  port: 8080


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}